"""One-call markdown lab report from stored results (ADR-0017, P4).

Assembles everything the store holds under a key into a readable report:
test summaries, strain-life fits, design curves, staircase analyses, basis
values, and variable-amplitude results, each with its provenance hash, and
the citation registry entries for the methods that appear. The report states
what it found and prints nothing for what is absent.
"""

from __future__ import annotations

from .citations import CITATIONS

__all__ = ["build_markdown"]

#: store kinds the report knows how to render, in report order
_KINDS = (
    "summary",
    "series_summary",
    "strain_life_fit",
    "design_curve",
    "staircase",
    "basis_value",
    "va_life",
)

#: citation registry keys relevant to each kind
_KIND_CITATIONS = {
    "summary": ("true_stress_strain", "coffin_manson", "basquin"),
    "series_summary": ("e606_reporting",),
    "strain_life_fit": ("basquin", "coffin_manson", "ramberg_osgood"),
    "design_curve": ("log_life_regression", "owen_design_curve",
                     "lack_of_fit_f_test"),
    "staircase": ("staircase_dixon_mood",),
    "basis_value": ("basis_values",),
    "va_life": ("va_local_strain_simulation", "swt", "morrow_mean_stress",
                "miner"),
}

_SCALAR_FMT = "{:.6g}"


def _fmt(value) -> str:
    if isinstance(value, float):
        return _SCALAR_FMT.format(value)
    return str(value)


def _table(d: dict, *, skip=("loops", "resolutions", "tests", "notes",
                             "counts", "files", "errors")) -> list[str]:
    lines = ["| quantity | value |", "|---|---|"]
    for k, v in d.items():
        if k in skip or isinstance(v, (dict, list)):
            continue
        lines.append(f"| {k} | {_fmt(v)} |")
    return lines


def _nested_tables(name: str, d: dict) -> list[str]:
    lines: list[str] = []
    for k, v in d.items():
        if isinstance(v, dict) and all(
            not isinstance(x, (dict, list)) for x in v.values()
        ):
            lines.append(f"**{k}**")
            lines.append("")
            lines.extend(_table(v))
            lines.append("")
    return lines


def build_markdown(key: str, records: dict[str, dict]) -> str:
    """Render the report for ``key`` from ``{kind: store_record}``."""
    found = [k for k in _KINDS if k in records and records[k]]
    lines = [
        f"# Fatigue analysis report: {key}",
        "",
        "Generated by lcf-strain-life from stored, provenance-hashed "
        "results. Every method cites its source at the end.",
        "",
    ]
    if not found:
        lines.append(f"No stored results were found under the key `{key}`.")
        return "\n".join(lines)

    cited: list[str] = []
    for kind in found:
        rec = records[kind]
        value = rec.get("value") or {}
        lines.append(f"## {kind.replace('_', ' ')}")
        lines.append("")
        lines.extend(_table(value))
        lines.append("")
        lines.extend(_nested_tables(kind, value))
        notes = value.get("notes")
        if notes:
            lines.append("Notes:")
            lines.extend(f"- {n}" for n in notes)
            lines.append("")
        if rec.get("input_hash"):
            lines.append(f"Provenance hash: `{rec['input_hash']}`")
            lines.append("")
        for ckey in _KIND_CITATIONS.get(kind, ()):
            if ckey in CITATIONS and ckey not in cited:
                cited.append(ckey)

    if cited:
        lines.append("## Sources")
        lines.append("")
        for ckey in cited:
            entry = CITATIONS[ckey]
            lines.append(f"- {entry['method']}: {entry['citation']}")
            if entry.get("note"):
                lines.append(f"  Note: {entry['note']}")
        lines.append("")
    return "\n".join(lines)
